import { defineType } from 'sanity';
export default defineType({
    name:"user",
    type:"document",
    title:"users",
    fields:[
        {
            name:"name",
            type:"string",
            title:"name",
            validation:Rule=>Rule.required()
        },
        {
            name:"location",
            type:"string",
            title:"location",
            validation:Rule=>Rule.required()
        },
        {
            name:"phone",
            type:"number",
            title:"phone",
            validation:Rule=>Rule.required()
        },
        {
            name:"adhaar",
            type:"number",
            title:"adhaar",
            validation:Rule=>Rule.required()
        },
        {
            name:"email",
            type:"string",
            title:"email",
            validation:Rule=>Rule.required()
        },
        {
            name:"password",
            type:"string",
            title:"password",
            validation:Rule=>Rule.required().min(6)
        },
        {  
            name:"is_donor",
            type:"boolean",
            title:"is_donor",
            validation:Rule=>Rule.required()
        }
    ] 
});